[build]
builder = "NIXPACKS"

[deploy]
startCommand = "dotnet run --project Bakery2048.API/Bakery2048.API.csproj"
healthcheckPath = "/swagger/index.html"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
